name: Automatic Deployment

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Welcome
        run: echo Start deploying Thieng API
      - name: Build docker
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tuphanson/thieng-api
          tags: latest
      - name: Run docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATEKEY }}
          script: |
            docker stop api
            docker rm api
            docker pull tuphanson/thieng-api
            docker run -d --name api tuphanson/thieng-api
            docker cp ./keys api:/home/thieng-api/configs/keys
            docker network connect --ip 172.18.0.3 thieng-net api
            docker image prune -a -f
